import type { Metadata } from 'next'
import './globals.css'
import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'
import Providers from '@/lib/providers'
import { config } from '@/lib/wagmi'
import AppKitProvider from '@/lib/providers'
import { XmtpProvider } from '@/context/XmtpContext'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang='en' suppressHydrationWarning>
      <Providers>
        <XmtpProvider>
          <body>
            <AppKitProvider initialState={initialState}>{children}</AppKitProvider>
          </body>
        </XmtpProvider>
      </Providers>
    </html>
  )
}
